export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const AGREGAR_TAREA_EXITO = 'AGREGAR_TAREA_EXITO';
export const AGREGAR_TAREA_ERROR = 'AGREGAR_TAREA_ERROR';

export const DESCARGA_TAREA = 'DESCARGA_TAREA';
export const DESCARGA_EXITO = 'DESCARGA_EXITO';
export const DESCARGA_ERROR = 'DESCARGA_ERROR';

export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ELIMINAR_EXITO = 'ELIMINAR_EXITO';
export const ELIMINAR_ERROR = 'ELIMINAR_ERROR';

export const EDITAR_TAREA = 'EDITAR_TAREA';
export const COMENZAr_EDITAR = 'COMENZAr_EDITAR';
export const EDITAR_EXITO = 'EDITAR_EXITO';
export const EDITAR_ERROR = 'EDITAR_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';